# Generated by Django 5.1.1 on 2024-09-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('time', models.TimeField()),
            ],
        ),
    ]
