# Generated by Django 5.1.1 on 2024-09-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userauthmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
