# Generated by Django 5.1.1 on 2024-09-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userauthmodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('token', models.CharField(max_length=8)),
            ],
        ),
    ]
